ITEM.name = "Hunter's Hood"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A lightweight hood made of animal pelt.."
ITEM.longdesc = "Coverage: Head\nPhysical: 1\nEnergy: 1\n Radiation: 0\nSpecial Qualities: Shadowed"
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1
