ITEM.name = "Raider Left Arm"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A scrappy arm piece. Better than nothing!"
ITEM.longdesc = "Coverage: Left Arm\nPhysical: 1\nEnergy: 1\n Radiation: 0"
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1
