ITEM.name = "Raider Left Leg"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A scrappy leg piece."
ITEM.longdesc = "Coverage: Left Leg\nPhysical: 1\nEnergy: 1\n Radiation: 0"
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1
