ITEM.name = "Missile Launcher Stabilizer"
ITEM.description = "A stabilizer that keeps rockets on track for longer after exiting the barrel."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 60
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.prefix = "Muzzled"
ITEM.effects = {"Piercing 1"}