ITEM.name = "Short Night Vision Scope"
ITEM.description = "An optic with a toggle for low-light optics, for use at standard engagements in darkness."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 38
ITEM.slot = 5
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.prefix = "Night Vision"
ITEM.qualities = {"Accurate"}
