ITEM.name = "Plasma Caster Pulse Capacitor"
ITEM.description = "A pulse capacitor that blasts out an electromagnetic pulse when it fires, affecting machinery."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 70
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 3
ITEM.prefix = "Pulse"
ITEM.qualities = {"Surge"}