ITEM.name = "Gatling Laser Beta Wave Tuner"
ITEM.description = "An oversized Beta Wave Tuner specifically for use in the Gatling Laser."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 57
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.prefix = "Incendiary"
ITEM.effects = {"Persistent"}