ITEM.name = "Gatling Gun Front Sight Ring"
ITEM.description = "A circular front sight that makes acquiring targets easier."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 158
ITEM.slot = 5
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.removeeffects = {"Inaccurate"}