ITEM.name = "Gatling Laser Photon Exciter"
ITEM.description = "An oversized Photon Exciter specifically for use in the Gatling Laser."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 19
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.prefix = "Excited"
ITEM.effects = {"Vicious"}