ITEM.name = "Flamer Long Barrel"
ITEM.description = "An extended barrel for Flamers that makes aiming your flames a tad easier."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 28
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.prefix = "Long"
ITEM.removequalities = {"Inaccurate"}