ITEM.name = "Barbed Baseball Bat"
ITEM.description = "A roll of barb wire to wrap around a baseball bat. Hot diggity dog!"
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0
ITEM.prefix = "Barbed"
ITEM.effects = {"Piercing 1"}