ITEM.name = "Sharpshooter's Grip"
ITEM.description = "A curved grip usually meant for easier bracing with rifle-grip weapons, but manages just fine for pistols as well."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0
ITEM.prefix = "Sharpshooter's"