ITEM.name = "Plasma Caster Calibrated Capacitor"
ITEM.description = "A calibrated capacitor for a Plasma Caster, allowing for more precise shots."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 140
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 3
ITEM.effects = {'Vicious'}
