ITEM.name = "Reflex Sight"
ITEM.description = "An optic with a red circle for quicker target acquisiton at closer ranges.\nAllows one re-roll of hit location die per turn"
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 14
ITEM.slot = 5
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0
ITEM.prefix = "Tactical"
