ITEM.name = "Minigun Gunner Sight"
ITEM.description = "A relatively simple but sturdy sight to have a better sense of where your shots are going."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 68
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.prefix = "Tactical"
ITEM.removeeffects = {"Inaccurate"}