ITEM.name = "Missile Launcher Scope"
ITEM.description = "A scope for easier target acquisition."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 143
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 6
ITEM.prefix = "Scoped"
ITEM.effects = {"Accurate"}