ITEM.name = "Sharp Knuckles"
ITEM.description = "Some crude blades for bleeding your opponents."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0
ITEM.prefix = "Sharp"
ITEM.effects = {"Persistent"}
