ITEM.name = "Calibrated Receiver"
ITEM.description = "A carefully calibrated receiver for tighter shot groupings."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 25
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0
ITEM.prefix = "Calibrated"
ITEM.effects = {"Vicious"}