ITEM.name = "Minigun Shredder"
ITEM.description = "A wrapping of barbed wire to wrap around a minigun's spinning barrels, turning it into a melee weapon in a pinch.\nMelee weapon, deals Physical damage equal to Rate of Fire"
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 5
ITEM.prefix = "Shredding"