ITEM.name = "Snub-Nose Barrel"
ITEM.description = "A shortened barrel for six-shooters that makes them easier to conceal within clothing, but sharply drops their accuracy."
ITEM.category = "Attachments"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = -1
ITEM.prefix = "Snub-Nosed"
ITEM.effects = {"Concealed", "Inaccurate"}
