ITEM.name = "T-51b Helmet"
ITEM.description = "The very first upgrade to T-51 armor. This version was ultimately the version shipped to Anchorage mechanized forces - partially because it didn't need much work to meet standards, and partially because it was being rushed out to service." 
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true
ITEM.armorHP = 1