ITEM.name = "Power Armor Hydraulic Bracers"
ITEM.description = "Some extra, springy 'oomf' to your punches.\nUnarmed attacks (fists only) gain +2 damage dice"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true