ITEM.name = "Power Armor Kinetic Dynamo"
ITEM.description = "Dynamos for a chest piece that convert kinetic force received into a bit of extra power.\nIf you suffer any damage after armor reductions, add +1 to the AP pool"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.isArmorUpg = true