ITEM.name = "Lighter Build"
ITEM.description = "Remove some unnecessary parts from an armor piece, slightly reducing its burden\n-1kg Armor Weight."
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = -1
ITEM.isArmorUpg = true
