ITEM.name = "X-01 MKII Helmet"
ITEM.description = "Second generation X-01 plating with improved performance." 
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 14
ITEM.slot = 1
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true
ITEM.armorHP = 1
