ITEM.name = "Power Armor Blood Cleanery"
ITEM.description = "A blood cleaning for a chest piece, like a less intense dialysis machine.\nRe-roll addiction chance dice"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.isArmorUpg = true