ITEM.name = "Power Armor Optimized Bracers"
ITEM.description = "Focused on speed, optimized bracers swing faster.\nCan spend +1 more AP on extra bonus die for all melee and unarmed attacks, for a total of 4, or 5 if paired"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true