ITEM.name = "Biocomm Mesh"
ITEM.description = "Add some extra science doohickeys onto your armor, it definitely works, trust me.\nChem duration is doubled"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 9
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 2
ITEM.isArmorUpg = true
ITEM.chemMultiplier = 2
