ITEM.name = "Power Armor Rad Scrubber"
ITEM.description = "A modification for power armor helmets, coming with a rad scrubber that cleans the rads from consumed food, which you evidently just shove right through your face plate for some reason.\nIgnores radiation from irradiated food and drink"
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100
ITEM.slot = 3
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true