ITEM.name = "Power Armor Titanium Plating"
ITEM.description = "Some additional plating for power armor pieces that shores up their defenses, making them ablate to enemy fire just a bit less. "
ITEM.category = "Upgrades"
ITEM.model = "models/mosi/fallout4/props/junk/modcrate.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10
ITEM.slot = 2
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 1
ITEM.isArmorUpg = true
ITEM.armorHP = 1
